### ISSUE TITLE
Crossbarr error

### ISSUE THREAD

**Issue by klipa-dev** [dappnode/DNP_WAMP#12]
After I tried moving docker data to another disk following this tutorial:
https://github.com/dappnode/DAppNode/wiki/Mount-docker-data-on-a-different-SSD

WAMP and VPN (because of WAMP) are not working, while other dockers seems to work correctly (ethchain is syncing node without any problems). 

Logs from VPN docker:
![image](https://user-images.githubusercontent.com/6116529/72932552-46ab2f00-3d60-11ea-8d4c-84481657a24f.png)

Logs from WAMP docker:
![image](https://user-images.githubusercontent.com/6116529/72932585-5460b480-3d60-11ea-848c-fc32ac684828.png)

When I ssh to WAMP docker I tried to find out what is missing:
```
~ $ ls /node
README.md         __pycache__       authenticator.py
~ $ ls /node/.crossbar
config.json  key.priv     key.pub
```

So it seems that node.pid is missing from here from `/node/.crossbar`, I saw that crossbar has issue opened with same error:
https://github.com/crossbario/crossbar/issues/1672

**Comment by klipa-dev** [comment]
I also tried uninstalling DappNode and then installing it again but I'm running into same problem

**Comment by vdo** [comment]
We are trying to reproduce this issue without luck. We will need to investigate this further

**Comment by pimentelleo** [comment]
I am having the same issue, trying to boot up a simple crossbar node with the above docker-compose.yml config (i'm using docker for running)

`version: "3"

services:

    crossbar:
        image: crossbario/crossbar
        container_name: crossbar-container
        restart: always
        ports:
            - 9010:9000
        volumes:
            - ../crossbar/development/.crossbar:/node
`

**Comment by dapplion** [comment]
Crossbar is no longer used in the DAppNode stack
