### ISSUE TITLE
Unnamed data volume

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_WAMP#3]
The volume created by WAMP container it's unnamed in the docker-compose and it's hard to identify when listing them:
```
root@DAppNodeVDO:~# docker volume ls
DRIVER              VOLUME NAME
local               73e1e7537bb0a8f93a7e39514317a4dc10f3e33a8ed9c80c7ecf1e99b7af49ce
local               dncore_binddnpdappnodeeth_data
local               dncore_dappmanagerdnpdappnodeeth_data
local               dncore_ethchaindnpdappnodeeth_data
local               dncore_ipfsdnpdappnodeeth_data
local               dncore_ipfsdnpdappnodeeth_export
local               dncore_vpndnpdappnodeeth_data
```
It should be named `dncore_wampdnpdappnodeeth_data` for consistency.

**Comment by vdo** [comment]
https://github.com/dappnode/DNP_WAMP/blob/16a42aef67e1718a602f08d2e532f69949034e45/build/Dockerfile#L48

@eduadiez Is this volume needed?

**Comment by dapplion** [comment]
It seems that the volume is needed but the docker-compose is really old and didn't follow the current naming conventions. @vdo can you please modify the docker-compose in a branch to fix the naming issue following the naming convention?
```
dncore_<DnpName>dnpdappnodeeth_data
```

**Comment by vdo** [comment]
I think we don't really need this volume, as we are not storing any data there apart from the authenticator script.
Can we remove it @eduadiez ?

**Comment by vdo** [comment]
https://github.com/dappnode/DNP_WAMP/pull/4
